### ISSUE TITLE
Version 1.0 installer won't run on Windows 10 64Bit.

### ISSUE THREAD

**Issue by aurialLoop** [Delicode/Vidiot#4]
The version 1.0 installer from your website: https://www.vidiot.wtf/ won't execute on Windows 10 64Bit.

When attempting to run it not in administrator mode: "This app can't run on your PC. To find a version for your PC, check with the software publisher."

When in administrator mode: Error "Windows cannot find 'C:\Vidiot_v1.00_Installer_x64.exe'. Make sure you typed the name correctly and try again."

**Comment by SirDifferential** [comment]
This was actually an error in the file name - the installer isn't an executable, but a zip file. We've fixed the file so it's now correctly a zip.
