### ISSUE TITLE
windows 10 lacking dependencies 

### ISSUE THREAD

**Issue by vdmokstati** [Delicode/Vidiot#5]
00:00:49.375: qrc:/qml/main.qml:22:1: module "QtQuick.Dialogs" is not installed
00:00:49.375: qrc:/qml/main.qml:19:1: module "QtQuick" is not installed
00:00:49.375: qrc:/qml/main.qml:24:1: module "QtAV" is not installed
00:00:49.391: qrc:/qml/main.qml:22:1: module "QtQuick.Dialogs" is not installed
00:00:49.391: qrc:/qml/main.qml:19:1: module "QtQuick" is not installed
00:00:49.391: qrc:/qml/main.qml:24:1: module "QtAV" is not installed
00:00:49.375: qrc:/qml/main.qml:22:1: module "QtQuick.Dialogs" is not installed
00:00:49.375: qrc:/qml/main.qml:19:1: module "QtQuick" is not installed
00:00:49.375: qrc:/qml/main.qml:24:1: module "QtAV" is not installed
00:00:49.391: qrc:/qml/main.qml:22:1: module "QtQuick.Dialogs" is not installed
00:00:49.391: qrc:/qml/main.qml:19:1: module "QtQuick" is not installed
00:00:49.391: qrc:/qml/main.qml:24:1: module "QtAV" is not installed
00:00:49.391: qrc:/qml/main.qml:22:1: module "QtQuick.Dialogs" is not installed
00:00:49.391: qrc:/qml/main.qml:19:1: module "QtQuick" is not installed
00:00:49.391: qrc:/qml/main.qml:24:1: module "QtAV" is not installed
00:00:49.407: First chance exception 0xC0000005 (Access Violation) occurred in "c:\working\vidiot\QT5CORE.DLL" at address 0x00000000668279AF.
00:00:49.407: Second chance exception 0xC0000005 (Access Violation) occurred in "c:\working\vidiot\QT5CORE.DLL" at address 0x00000000668279AF.

**Comment by SirDifferential** [comment]
Thanks for reporting this. We had forgotten to bundle the QML dlls. 1.01 is now out with the files included. http://vidiot.wtf/
